### ISSUE TITLE
/platform:anycpu32bitpreferred set for library projects.

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpDevelop#244]
[SD-1929](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1929), originally created on 10/20/2013 11:10:03 by Matt Ward

See forum:

[http://community.sharpdevelop.net/forums/t/19665.aspx](http://community.sharpdevelop.net/forums/t/19665.aspx)

To reproduce:

1) Create a new C# class library project that targets .NET 4.5 in
Visual Studio.
2) Open the same project in SharpDevelop.
3) Open the project properties and select the Compile tab.

Expected result:

The project properties and project file are unchanged since the user has
not changed anything.

Actual result:

The project properties are changed when the Compile tab is selected. On
saving the project and compiling you get an error:

 Error CS4023: /platform:anycpu32bitpreferred is not a valid setting for
option /target:library or /target:module

**Comment by asd-and-Rizzo** [comment]
I still see issue on
```
SharpDevelop Version : 5.1.0.4936-Beta-3ea20cfa
.NET Version         : 4.5.50938
OS Version           : Microsoft Windows NT 6.1.7601 Service Pack 1
Current culture      : English (United States) (en-US)
Running under WOW6432, processor architecture: x86-64
Working Set Memory   : 236104kb
GC Heap Memory       : 59895kb
```
Opened csproj files and deleted manually new entries. Reproduced on https://bitbucket.org/dadhi/dryioc/branch/edge DryIoc.ResolutionGraphGeneration.sln.
