### ISSUE TITLE
Problems with Templates & StaticResources in XAML Parser.

### ISSUE THREAD

**Issue by jogibear9988** [icsharpcode/SharpDevelop#602]
I've fixed the SharpDevelop XAML Parser to use the Microsoft One for WPF Templates! At first I wanted to use the SD one, and create FrameworkElementFactories for the Template Parts, but that is not supported from MS, not all you can do in a Template can be done via the FramweworkElementFactories, so I switched to use the MS Xaml Parser for them.

Now I have the following Problem: If you define a Resource wich you later use in a Template via StaticResource, the XamlParser throws an error, because he could not find that Resource (same for Resources defined in App.Xaml). I wanted to know, is there a way that I can say to the MS Xaml Parser where too look for Aditional Resources? I've allready seen in the Code of the StaticResourceExtension, that the Parser uses "GetAllAmbientValues" to find the Resources, but I'm not able to change the MS Xaml parser to use our "IServiceProvider" so that also our "IAmbientProvider" will be used. Has anyone a Idea?

**Comment by giuliohome** [comment]
I've done a quick test of the above branch. It looks like it is able to show the styles in the Resources section of the xaml but it lacks support for a ResourceDictionary. Is it also under development? Thank you

**Comment by jogibear9988** [comment]
The Code from my Branch is in main SD, so you don't need to test the Branch!

At the Moment im not working on adding more support. What is not workin? I don't understand your error...

**Comment by giuliohome** [comment]
Sure, thanks. I've seen that it is in the main beta and I've tested that too. If I have a resource dictionary generic.xaml in the window plus a specific texblock style in a contained stackpanel (code of xaml is in the linked SO answer) the margin set in the generic.xaml are missing.

**Comment by giuliohome** [comment]
I've also posted a question in the forum http://community.sharpdevelop.net/forums/p/22137/56558.aspx#56558

**Comment by giuliohome** [comment]
Generic.xaml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
            <Style x:Key="BasicStyle" TargetType="TextBlock">   
                <Setter Property="Margin" Value="20,20,30,20" />
            </Style>
            <Style TargetType="TextBlock" BasedOn="{StaticResource BasicStyle}">
</ResourceDictionary>
And wilndow1.xaml
<Window x:Class="MergedDictionaries.Window1"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MergedDictionaries" Height="300" Width="300">
    <Window.Resources>
            <ResourceDictionary Source="pack://application:,,,/Generic.xaml" />
    </Window.Resources>
    <StackPanel>
        <StackPanel.Resources>
            <Style TargetType="TextBlock"  BasedOn="{StaticResource BasicStyle}">
                <Setter Property="Background" Value="Aquamarine" />
            </Style>
        </StackPanel.Resources>
        <TextBlock Text="First Block" />
        <TextBlock Text="Second Block" />
    </StackPanel>
</Window>
