### ISSUE TITLE
SplitView in Code Editor !

### ISSUE THREAD

**Issue by jogibear9988** [icsharpcode/SharpDevelop#639]
I've seen that the Split View in SD was removed!

Is there any reason for this? Was this a design decission, or is it possible to get it back when I work on this?

**Comment by siegfriedpammer** [comment]
It would have been a lot of work to port it properly to the new architecture. We then looked at the usage data we collect and saw that it was not used often.

Therefore we decided to simply remove it instead of putting a lot of work into a mostly unused feature.
