### ISSUE TITLE
Is there a way to compile SharpDevelop on Linux?

### ISSUE THREAD

**Issue by wind39** [icsharpcode/SharpDevelop#656]
First of all, sorry about my bad English.

When I was using Windows, let's say 5 years ago, I enjoyed SharpDevelop. But now I use only Linux, and I use MonoDevelop, but I miss SharpDevelop, especially the Windows Forms designer.

Thanks in advance! :)

**Comment by christophwille** [comment]
No, there isn't. MonoDevelop is the way to go.
