### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by schiplonkar** [icsharpcode/SharpDevelop#670]
Every time I build the VB solution in the Sharp develop I get this warning. The build finishes and works fine though.
The reference assemblies for framework ".NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

**Comment by mrward** [comment]
To fix this warning you should install the [Windows SDK](https://msdn.microsoft.com/en-us/windows/desktop/bg162891.aspx) that includes the reference assemblies for .NET 4.5.1.
