### ISSUE TITLE
I have visual studio 2013, and it is not compiling in it

### ISSUE THREAD

**Issue by adageamar** [icsharpcode/SharpDevelop#722]
In version 5.0 I dont able to find report, while creating new file, so I had downloaded the code, but I have visual studio 2013 and while compiling it is giving error.
What to do???

**Comment by mrward** [comment]
To build SharpDevelop from source you can use the [debugbuild.bat file](https://github.com/icsharpcode/SharpDevelop/blob/master/debugbuild.bat)
