### ISSUE TITLE
Unit Test window

### ISSUE THREAD

**Issue by ddur** [icsharpcode/SharpDevelop#726]
When using test data source, where some data fails, 
following item that is successful, overwrites "red" status to "green" again.

**Comment by lvv83** [comment]
[TestCaseSource] & [TestCase] attributes doesn't supported by UnitTesting Addin

**Comment by ddur** [comment]
As far as I remember it was supported. Try some older versions.

**Comment by lvv83** [comment]
> Try some older versions.

Thanks, but I can use SD just for fun, but not for production... sad to say :(

I look at last SD4 source code, and there is only [TestFixture] & [Test] attributes respected (like SD5) 
There is no full NUnit tests integration (#177) including [TestCase] support.

**Comment by ddur** [comment]
There is no need for integration with those attributes.
It takes only to check if test is marked failed (red), then do not overwrite with next successful one (green).
If previous test is success (green) and next test is failed then overwrite (red)

**Comment by lvv83** [comment]
Can't reproduce. Fail is red, Pass is green.
SharpDevelop Version : 5.1.0.5134-RC-d5052dc5

```csharp
using System;
using NUnit.Framework;

namespace FooTest
{
	[TestFixture]
	public class MyClass
	{
		[Test]
		public void Fail()
		{
			Assert.Fail();
		}
		
		[Test]
		public void Pass()
		{
			Assert.Pass();
		}
	}
}
```

**Comment by ddur** [comment]
Yes, but child (leaf) is changing color for each [TestCase].
If all TestCase data failed, but last is success, then child is green (and parents too).
Just do not overwrite red node.

**Comment by ddur** [comment]
```
using System;
using NUnit.Framework;

namespace FooTest
{
    [TestFixture]
    public class MyClass
    {
        [Test]
        public void Fail()
        {
            Assert.Fail();
        }

        [TestCase(false)]
        [TestCase(true)]
        public void Pass(bool case)
        {
            Assert.Pass(case == true);
        }
    }
}
```

**Comment by lvv83** [comment]
First, I can't compile your sample. May be it because I use another version of NUnit assembly (v. 2.6.4).
```csharp
		[TestCase(false)]
		[TestCase(true)]
		public void Pass(bool @case)
		{
			if (@case)
				Assert.Pass();
			else
				Assert.Fail();
		}
```

Second, [TestCase] attribute used, which support... read above.

Current test model implementation doesn't see difference between [Test] and [TestCase] attributes. There are next types for treeview items: test project, test namespace, test class and test method. Test method is leaf node without children. Then test code goes to NUnit console, but SD takes only first result and pass it to the treeview.

**Comment by ddur** [comment]
I'm using those tests with [TestCase] attribute in SharpDevelop for at least 2 years.
https://github.com/icsharpcode/SharpDevelop/pull/67
Cannot find my older contributions for SharpDevelop 4

**Comment by ddur** [comment]
@lvv83 
Can you try this please?
```
		void ChangeResult(TestResultType newResult)
		{
			TestResultType oldResult = result;
-----------------------------------------------------------------------------------------------------------------------
			if (oldResult == TestResultType.Failure && newResult == TestResultType.Success) {
				return; // do not change result result from failure to success
			}
-----------------------------------------------------------------------------------------------------------------------
			if (oldResult != newResult) {
				result = newResult;
				OnResultChanged(new TestResultTypeChangedEventArgs(oldResult, newResult));
			}
		}
```
It works for me.

**Comment by lvv83** [comment]
@ddur 
Sorry, but I don't understand how I should run this code and what for?

I had the same problem with UnitTest Window, and perform code researching of SD5. I just try to explain reasons of this issue, nothing more.

I think that each [TestCase] attribute should be presented as specific tree node - child of test method node (you can see an example at NUnit GUI). But I haven't much experience with NRefactory to implement this.

You may provide a pull request to SD repo admins (I'm not).
Thanks.

**Comment by ddur** [comment]
Sorry, I thought you are maintainer of NUnit plugin :)
