### ISSUE TITLE
Provide downloads via GitHub releases

### ISSUE THREAD

**Issue by boughtonp** [icsharpcode/SharpDevelop#739]
The [download page](http://www.icsharpcode.net/OpenSource/SD/Download/) redirects to SourceForge, which regrettably now is a [source of malware](http://blog.gluster.org/2013/08/how-far-the-once-mighty-sourceforge-has-fallen/), and thus not a reputable source to download from.

Simple solution is to attached the binary files to the relevant [GitHub releases](https://github.com/icsharpcode/SharpDevelop/releases).

**Comment by ddur** [comment]
Why not use free [AppVeyor](https://ci.appveyor.com/) to build?

**Comment by boughtonp** [comment]
If that's an official recommendation, the download page needs updating with the relevant information.

**Comment by christophwille** [comment]
The downloads will stay where they are for the time being. That's an official response from the release manager (me).

**Comment by boughtonp** [comment]
_\*shrug*_ Your choice.

Be aware that some anti-malware software will block access to SourceForge (as a whole), and wilfully supporting a malware supplier is not going to help the reputation of the project.

**Comment by christophwille** [comment]
Please leave.

**Comment by siegfriedpammer** [comment]
Don't want to heat up the discussion again, but it seems that you DID NOT EVEN TRY what happens when you download SharpDevelop from SourceForge: yes, you get OUR installer built with WiX. Seems you are not quite up to date.

Try it here: http://sourceforge.net/projects/sharpdevelop/ (yes, the big green button leads to our 15.6 MB MSI package, no ad-ware/malware included.)

**Comment by boughtonp** [comment]
There's no heat on this side, and I had no intention of commenting further, but:

1) SourceForge is blocked. The whole site. I could bypass that, but others may not be able to.

2) You only know the installer isn't wrapped because you checked - it has been done without permission in the past, and there's no guarantee there will continue to be an indication of when it has been done.

3) Hosting files on SourceForge is accepting and encouring their behaviour. I don't trust any project that does so and won't use it.

That's all I have to say; soon as this comment goes through I'm unsubscribing and wont respond further.
(There's a Lock conversation option to the right, feel free to use it.)

**Comment by jogibear9988** [comment]
When you look at wikipedia (https://de.m.wikipedia.org/wiki/SourceForge), you see he's right, that sourceforge had modified installer packages in the past...
