### ISSUE TITLE
How to launch Addin Package Management from standalone PM

### ISSUE THREAD

**Issue by xuanzhaopeng** [icsharpcode/SharpDevelop#747]
Hi, All,

I clone all source code and want to know how to run Package Management from PM, but failed...

What I did is : 
[Environment]::Is64BitProcess // To check current PM version is 32bit

Set-ExecutionPolicy RemoteSigned -Scope Process

import-module "C:\Test\PackageManagement\PackageManagement.Cmdlets.dll"

Could anyone help me?

Thanks a lot

**Comment by mrward** [comment]
Failed how exactly? What was the error? What branch of the source code are you using?

**Comment by xuanzhaopeng** [comment]
@mrward  Hi, I check all.. I use branch master/ 4.1 / 4.2, and the exception is cannot init the type of ICSharpCode.PackageManagement.PackageManagementServices 

I do some code review, I found the all service haven't start when I load the dll into PM... 

And I also decompile the dll from http://community.sharpdevelop.net/blogs/mattward/archive/2011/06/12/InstallingNuGetPackagesOutsideVisualStudio.aspx

I found the dll of PackageManagement.Cmdlets.dll are different ... the logic are totally different 

Any help...

**Comment by mrward** [comment]
You are using the wrong source code if you are trying to use the source from icsharpcode/SharpDevelop. At the end of that blog post you will find a link to the [GitHub repository and the branch](https://github.com/mrward/SharpDevelop/tree/nuget). It is my own fork of the main SharpDevelop and it is not up to date. The last change was made back in 2013.

**Comment by xuanzhaopeng** [comment]
@mrward  Thanks a lot, it's my mistake...I try to update it to work with Nuget 2.8

Thanks a lot

**Comment by xuanzhaopeng** [comment]
@mrward  Coooool ! The last version of Nuget is 2.7!  I will close this issue cause It is perfect!

Thanks a again
