### ISSUE TITLE
Master branch has build errors when used with latest version of Mono.Cecil

### ISSUE THREAD

**Issue by rusanov-vladimir** [icsharpcode/SharpDevelop#776]
I've cloned latest version of SharpDevelop repo and then cloned one by one libraries indicated including Mono.Cecil. OnBuild I got errors because in latest version of Mono:
1. `Mono.Cecil.Cil.VariableReference` doen't contain anymore property `Name`, that is extensevly used in SharpDevelop
2. Mono.Cecil.TypeDefinition.Interfaces property changed type from `Collection<TypeReference>` to `Collection<InterfaceImplementation>`. SharpDevelop relying code failing on type conversion after this change.

I've fixed these issues locally, but is it me doing something wrong and I should've used specific revision of Mono.Cecil to build SharpDevelop?

**Comment by mrward** [comment]
The SharpDevelop repository points to specific commits in all its submodules. It is not guaranteed to work with other revisions. You should be able to update your submodules to point to the correct revisions by running `git submodule update`.
