### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by geek1011** [icsharpcode/SharpDevelop#783]
I use Sharpdevelop for c# development. I like it more than VS for the following reasons:

- It is faster than VS
- It is open source
- It runs portable (this is a must for me as I often code on computers which I do not have control over)
- It is small (I often reinstall, and II also need to use a VM sometimes)
- It is not bloated
- And a few more reasons which I do not remember off the top of my head

So now for the questions: 

1. Is this project dead?
2. Are there any plans for a future release?
3. If there is not any more updates, to what extent will the newer .net versions continue to work with SharpDevelop 5?

**Comment by christophwille** [comment]
It has been dormant a couple of times during its lifetime. So far nobody has stepped forward to running the project this time. As pointed out in the SD Developer Days [post](http://community.sharpdevelop.net/blogs/christophwille/archive/2016/05/17/developer-days-2016-this-time-in-november.aspx) the former SD team members are working on side projects these days.

**Comment by awr-reb** [comment]
christophwille - I am new to SharpDevelop but agree with what geek1011 has said.  Perhaps, if the web page (icsharpcode.net & sharpdevelop.net) could be updated to let users know help is needed more will come forward.  It would be nice to see the db components work like in Visual Studio and/or Delphi, with more programming support this could happen.

**Comment by geek1011** [comment]
See also #799

**Comment by ZanderBrown** [comment]
Alternately close #799 as a duplicate
