### ISSUE TITLE
Compile error CS1502 + CS1503 when adding AutoUpdater.NET via NuGet package manager

### ISSUE THREAD

**Issue by rob1189** [icsharpcode/SharpDevelop#813]
Hi guys,

first of all I want to thank you for the job you've done for this incredible project, for many aspects it's even better than Visual Studio in my opinion.
Now, I was trying to add the AutoUpdater.NET reference by installing the package via NuGet: it correctly adds the reference to the "References" section of my project, then I add the 

`using AutoUpdaterDotNET;`

at the top of my MainForm.cs file and, in the "OnFormLoad()" method I add the line 

`AutoUpdater.Start("http://rbsoft.org/updates/AutoUpdaterTest.xml");`

When I try to compile, I get two errors:

- The best overloaded method match for 'AutoUpdaterDotNET.AutoUpdater.Start(System.Reflection.Assembly)' has some invalid arguments. (CS1502)
- Argument '1' cannot convert from 'string' to 'System.Reflection.Assembly'. (CS1503)

The autocompletion system tells me that the method start() appears first with the overload:
(1 of 2) `public static void Start(Assembly myAssembly = null);`

while the other (the one I need) is:

(2 of 2) `public static void Start(string appCast, Assembly myAssembly = null);`

It seems as if SharpDevelop could not detect overloads for the functions contained in AutoUpdater.NET reference but just the first one.
I tried the same steps in Visual Studio and it works perfectly.

Is this a bug with SD or NuGet package manager?

Thanks.
Kind regards,
Rob

**Comment by rob1189** [comment]
Compiler version C# 3.0, .NET target framework 3.0.

**Comment by subchannel13** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments

Optional parameters are C# 4 feature, try increasing compiler version.

**Comment by rob1189** [comment]
Uhm.. maybe I was a bit outdated? I usually tend to stay to the lower version possible just in favor of higher compatibility, but I need to reconsider advantages of using new versions (and since Windows 8 the minimum preinstalled version is 4.5).

However, this simple advice solved my problem. Thank you really much for your time!
